---
abstract: 'Perl5 module for text based look up table operations'
author:
  - 'Jeremiah Mahler <jmmahler@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-LookUpTable
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 0
  Text::Aligner: 0
  perl: 5.6.1
resources:
  homepage: http://search.cpan.org/dist/Text-LookUpTable/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jmahler/libtext-lookuptable-perl
version: 0.03
